### ISSUE TITLE
How to fix THIS error? Is it even possible?

### ISSUE THREAD

**Issue by copyandexecute** [Nirusu99/ytd-rs#2]
Hi I'm on windows and I get this error

```
Error: IOError(Error { kind: NotFound, message: "program not found" })
error: process didn't exit successfully: `target\debug\rust-testing.exe` (exit code: 1)

Process finished with exit code 1
```

How can I fix it? My path contains the yt-dlp.exe

**Comment by narrrl** [comment]
Sadly, I don't have any windows machines currently at hand. Could you test https://github.com/Nirusu99/ytd-rs/commit/011ee979c52726fbba7c832f144d590b49aa4814?

In `Cargo.toml`:
```toml
[dependencies]
ytd-rs = { git = "https://github.com/nirusu99/ytd-rs", branch = "main" }
```

**Comment by copyandexecute** [comment]
hey man nice commit, but I still can't get it running maybe I'm too stupid gonna check it at another time

**Comment by narrrl** [comment]
No problem, I have zero idea of development on windows. I'll make a Windows-VM and try to fix it tonight.

**Comment by narrrl** [comment]
Oh, just realized what the problem is. Have you enabled the `yt-dlp` feature? The default application is `youtube-dl`.

```toml
[dependencies]
ytd-rs = { version = "^0.1", features = ["yt-dlp"] }
```
